# Name of the model:
Example_Model:
# --------------------
# Example setup
# --------------------
# Required values:
  # brief description of the model, so users know what they are using.
  description: "an example model to show how to format the yaml files"
  # where to find it?
  # For this you will need to supply either:
  image_file: null # The absolute path to a local container image
  # OR
  repo_url: "docker://alpine:latest" # an OCI link to dockerhub (string stating with docker://)
# --------------------------------------
# Optional values:
  # Note: The users home directory is accessible by default.
  # This is for specifying any additional directories you wish
  # to access
  shared_directories: null
#--------------------------------------
Example_Model2:
  description: "another example model to show how to format the yaml files" 
  image_file: null # Note this will not work 