[project]
name = "bede-containers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dacite>=1.9.2",
    "pytest>=8.4.2",
    "pyyaml>=6.0.3",
]
