# This is a vaild dummy continer config to test with
Example_Model1:
  description: 'testing'
  image_file: null
  repo_url: "docker://alpine:latest"
  shared_directories: null

Example_Model2:
  description: 'testing'
  image_file: null
  repo_url: "docker://alpine:latest"
  shared_directories: null
